# Generated by Django 4.2 on 2023-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageClassification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='image_representative',
            field=models.ImageField(blank=True, null=True, upload_to='classes_representatives/'),
        ),
    ]
