# Generated by Django 4.2 on 2023-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageClassification', '0002_classe_image_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
