# Generated by Django 4.2 on 2023-04-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageClassification', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
